name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old runs
        uses: yanovation/delete-old-actions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days-ago: 7
          dry-run: false     # Set to false when ready to permanently delete
